site_name: SAGE Documentation
site_description: 高性能分布式推理框架 - 数据流原生的模块化、透明、可控的LLM工作流推理框架
site_author: IntelliStream Lab
site_url: https://sage.org.ai/
docs_dir: docs_src

theme:
  name: material
  custom_dir: theme

nav:
  - 首页: index.md
  - 关于: about.md
  - 入门: getting-started/index.md
  - 教程:
      - 教程总览: tutorials/index.md
      - 基础教程: tutorials/basic/streaming-101/index.md
      - 高级教程: tutorials/advanced/index.md
  - 用户指南: guides/index.md
  - API 参考: api-reference/index.md
  - 错误页: 404.md
